### ISSUE TITLE
#1 - Implement main menu & restartgame

### ISSUE THREAD

**Issue by 666uragan666** [trpo2021/cw-is-042_100_matches#2]
- Main Menu должно иметь структуру:
1. Вывод названия игры
Игра "100 спичек"

2. Вывод правил игры
Правила игры: "Из кучки, первоначально содержащей 100 спичек, двое играющих поочередно берут по несколько спичек: не менее одной и не более десяти. Проигрывает взявший последнюю спичку."

3. Выбор режима игры/ выхода 
Выберите режим игры:
1 - Против локального игрока
2 - Против Лёгкого ИИ
3 - Против Сложного ИИ
4 - Выйти из игры

- Так же в main функции необходимо реализовать вывод победителя с выбором: Повторить игру/ Выйти в меню

Пример вывода:
Победил - Player 1

Введите:
5 - Чтобы повторить игру
6 - Чтобы выйти в меню

При 5 - Повторяется раннее выбранный режим
При 6 - Отрисовывается Main Menu

**Comment by dizing** [comment]
Логика меню реализована.
Тесты не пишутся, из-за неудобства тестирования пользовательского ввода-вывода.
Вызовы функции game закоммичены, пока функция ещё не разработана, поэтому issue не закрыт.
После реализации game расскомитить вызовы и закрыть issue.
