### ISSUE TITLE
#3 - Implement real player input function

### ISSUE THREAD

**Issue by 666uragan666** [trpo2021/cw-is-042_100_matches#4]
Встречает игрока надпись -  Введите количество спичек, которое хотите взять:
В функции есть ввод с проверкой на корректность.
Игрок должен ввести сколько спичек он хочет взять (от 1 до 10).
Функция возвращает в game кол-во спичек, взятых игроком.

**Comment by dizing** [comment]
Ввод с консоли реализован.
Функция не тестируется, потому что состоит полностью из консольных вводов и выводов.
